name: "aegis"

services:
  aegis-api:
    container_name: aegis-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    env_file:
      - .env
    ports:
      - "8080:${APP_API_PORT:-8080}"
    networks:
      - aegis-network
    working_dir: /app
    volumes:
      - .:/app

networks:
  aegis-network:
    driver: bridge
